version: "2"
services:
  springgateway:
    labels:
      kompose.service.type: loadbalancer # need this label for Kubernetes
    image: bramco/brams6gateway
    hostname: frontend
    ports:
      - 443:443
      - 80:80
    restart: always
