version: '3.5'

services:
  api-gateway:
    image: 'hrajr25/api-gateway:v0.1'
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    container_name: api-gateway
    hostname: api-gateway
    restart: unless-stopped
    ports:
      - "8081:8081"