zuul:
  routes:
    user-service:
      service-id: UserService
      path: /user/**
      url: "http://userservice/"
      strip-prefix: true
    message:
      service-id: rabbitmq
      path: /message/**
      strip-prefix: true
      url: "http://messageservice/"
    logging:
      service-id: logging
      path: /logging/**
      strip-prefix: true
      url: "http://loggingservice/"

