zuul:
  routes:
    user-service:
      service-id: UserService
      path: /user/**
      url: "http://userservice/"
      strip-prefix: true
    rabbitmq:
      service-id: rabbitmq
      path: /rabbit/**
      strip-prefix: false
      url: "http://rabbitmq:15672/"
