apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-gateway
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
# apiVersion: v1
# kind: Service
# metadata:
#   name: api-gateway
# spec:
#   ports:
#     - protocol: TCP
#       port: 8081
#       targetPort: 8081
#   selector:
#    app: api-gateway
#  type: LoadBalancer
#status:
#   loadBalancer:
#     ingress:
#       - ip: 192.0.2.127
  #type: LoadBalancer