apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: spring-gateway-ingress
spec:
 rules:
 - http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        serviceName: springgateway
        servicePort: 8080