apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-gateway-ingress
spec:
  rules:
  - host: 165.232.88.89
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: springgateway
            port:
              number: 8081